# Generated by Django 4.2.24 on 2025-09-06 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('task_assigned', 'Tarea Asignada'), ('task_completed', 'Tarea Completada'), ('task_overdue', 'Tarea Vencida'), ('project_assigned', 'Proyecto Asignado'), ('project_completed', 'Proyecto Completado'), ('comment_added', 'Comentario Agregado'), ('deadline_reminder', 'Recordatorio de Fecha Límite'), ('general', 'General')], default='general', help_text='Tipo de notificación', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', help_text='Prioridad de la notificación', max_length=10)),
                ('title', models.CharField(help_text='Título de la notificación', max_length=200)),
                ('message', models.TextField(help_text='Mensaje de la notificación')),
                ('is_read', models.BooleanField(default=False, help_text='Indica si la notificación ha sido leída')),
                ('read_at', models.DateTimeField(blank=True, help_text='Fecha y hora en que se leyó la notificación', null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Datos adicionales en formato JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(help_text='Usuario que recibe la notificación', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_project', models.ForeignKey(blank=True, help_text='Proyecto relacionado (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='projects.project')),
                ('related_task', models.ForeignKey(blank=True, help_text='Tarea relacionada (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tasks.task')),
                ('sender', models.ForeignKey(blank=True, help_text='Usuario que envía la notificación (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notifications_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['type'], name='notificatio_type_ea918f_idx'), models.Index(fields=['priority'], name='notificatio_priorit_bf8ea0_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
    ]
